export const LOGIN_VISIBLE_STATE = "LOGIN_VISIBLE_STATE"; // 登录

export const REGISTER_VISIBLE_STATE = "REGISTER_VISIBLE_STATE"; // 注册

export const UPLOAD_VISIBLE_STATE = "UPLOAD_VISIBLE_STATE"; // 上传